# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'GiphyExplorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	# Pods for GiphyExplorer

  	# for displaying gifs in imageview
	pod 'SDWebImageFLPlugin'

  target 'GiphyExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
