platform :ios, '12.0'

target 'GiphyExplorer' do
  use_frameworks!
  
  # Pods for GiphyExplorer
  
  # for displaying gifs in imageview
  pod 'SDWebImageFLPlugin'
  
  target 'GiphyExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
